### ISSUE TITLE
AP mode or Client mode tcp reconnection problems

### ISSUE THREAD

**Issue by nowire** [arduino-libraries/WiFi101#235] opened 2018-06-15 06:24 UTC
thank you for the big job on this library.

I have one problem on a MKR1000. I try to explain it. The problem seems the same in AP or Client wireless mode.

I set my AP mode on MKR1000 and than try to connect to my tcp server. Connection was good and from client side i send to server every second some information.
When the server loss the wireless connection, the client dose not have information about this. Send metod is ok and I have no error.
I have added some information for take a wireless disconnection info and close the tcp socket. It works fine but when I try to reconnect to server I have a long timeout between two retry.

What can be the problem in my situation?

Massimiliano

**Comment by sandeepmistry** [comment] 2018-07-23 18:57
Hi @nowire,

This is related to #46.

I will close this issue as a duplicate of #46 for now.

**Closed by sandeepmistry** 2018-07-23 18:57 UTC
Labels: Waiting for Atmel, duplicate
