### ISSUE TITLE
Cant even complile examples for wifi101 and arduino 101

### ISSUE THREAD

**Issue by a2liter** [arduino-libraries/WiFi101#63] opened 2016-04-30 10:36 UTC
When I try to compile the example sketch to scan for available networks I get the following error.

I am running IDE 1.6.9 hourly build 2016/04/28 4:33

The board I have selected is Arduino 101

I am running library wifi101 0.9.0

I have read through all the forum posts I can find and I think I am doing all the suggested fixes for this issue.

C:\Users\chris\Documents\Arduino\libraries\WiFi101\src\WiFiMdnsResponder.cpp: In member function 'bool WiFiMDNSResponder::parseRequest()':

C:\Users\chris\Documents\Arduino\libraries\WiFi101\src\WiFiMdnsResponder.cpp:152:61: error: 'memcmp_P' was not declared in this scope

     if (memcmp_P(request, expectedRequestHeader, HEADER_SIZE) == 0 &&            // request header match

                                                             ^

C:\Users\chris\Documents\Arduino\libraries\WiFi101\src\WiFiMdnsResponder.cpp:154:72: error: 'strncasecmp' was not declared in this scope

         strncasecmp(name.c_str(), (char*)requestName, requestNameLength) == 0 && // name match

                                                                        ^

exit status 1
Error compiling for board Arduino 101.

**Comment by akash73** [comment] 2016-05-02 10:10
confirmed here, same behaviour.
first workaround is downgrade to 0.8.0 Wifi101 library version which works.

**Comment by sandeepmistry** [comment] 2016-05-02 12:58
I'm closing this as a duplicate of #51.

Now that https://github.com/01org/corelibs-arduino101/pull/159 has been merged, it will be resolved in the next 101 core release. Suggested work around for now is as @akash73 mentioned, downgrade to 0.8.0 of the library.

**Closed by sandeepmistry** 2016-05-02 12:58 UTC
