### ISSUE TITLE
 WiFiClient::write can last forever

### ISSUE THREAD

**Issue by klausj1** [arduino-libraries/WiFi101#182] opened 2017-06-16 14:54 UTC
Hi,

the method  WiFiClient::write does not have a timeout, and in some cases (I do not know when this happens), it can last forever.

I used the WiFi-Library from [here](https://github.com/klausj1/WiFi101/blob/master/src) (its a 0.14.3 with additional logs, and some minor changes), and get this logfile (only in very rare cases): 
```
"15.06.2017 15:41:51",Host: WiFiClient::write: Sending Buffer took more than 5 seconds!!! Duration: 60000
"15.06.2017 15:42:51",!!!IS_CONNECTED: 1
```
So I think the method should get a timeout.

Regards,
Klaus

**Comment by hoblins** [comment] 2017-08-21 18:47
Hello,
I'm using the Feather M0 Wifi as a sensor node. The node sends some sensor values every minute to a server with an HTTP post request. Unfortunately not perfectly reproducible, the board regularly (couple of hours up to 2-3 days) hanged during data transfer (transfer LED turned on).
The patch from @klausj1 reduced the error to almost zero.
Best

**Comment by sandeepmistry** [comment] 2017-10-18 21:08
Hi @klausj1,

Could you please submit a pull request for the specific changes to fix the issue. Thanks.

**Comment by klausj1** [comment] 2017-10-19 18:01
OK, I will do, but I will need some time for this.

**Comment by klausj1** [comment] 2017-11-25 21:43
Hi @sandeepmistry,

the pull request has been created, I hope everything is OK.

Klaus

**Comment by sandeepmistry** [comment] 2018-01-02 14:36
Closing this since PR #204 has be merged, which based on @klausj1's feedback has resolved this.

**Closed by sandeepmistry** 2018-01-02 14:36 UTC
Labels: waiting for feedback
