### ISSUE TITLE
AP Mode.  Unable to re-connect

### ISSUE THREAD

**Issue by driverblock** [arduino-libraries/WiFi101#110] opened 2016-10-17 18:18 UTC
Sample code attached.
Code creates an AP, then starts an HTTP server.  Server works normally.  If you disconnect computer from AP and then reconnect, Browser is no longer able to connect to server.
Adafruit forum thread here:
https://forums.adafruit.com/viewtopic.php?f=57&t=104876&p=525448#p525215

(also, statement  if (WiFi.beginAP(ssid) != WL_CONNECTED) { always fails, but AP is still created. What is correct test?)

`#include <WiFi101.h>
#include <WiFiClient.h>
#include <WiFiServer.h>
#include <WiFiUdp.h>

#include <SPI.h>
//#include <Adafruit_WINC1500.h>

// Define the WINC1500 board connections below.

#define WINC_CS   8
#define WINC_IRQ  7
#define WINC_RST  4
#define WINC_EN   2     // or, tie EN to VCC

// Setup the WINC1500 connection with the pins above and the default hardware SPI.
//Adafruit_WINC1500 WiFi(WINC_CS, WINC_IRQ, WINC_RST);

// **** WARNING ****
// If running this example on an Uno or compatible you MUST change the LED_PIN
// value below from 13 to something else that doesn't conflict with the SPI
// pins.  Try pin 9 for example.
// **** WARNING ****
#define LED_PIN  13  // This example assumes you have a LED connected to pin 13
// (with a resistor to limit current!).  Connect LED anode
// (longer leg) to pin 9, then LED cathode (shorter pin)
// through a resistor (~300-1k ohm) to ground.

#define a_button 9
#define b_button 6
#define c_button 5

char ssid[] = "Load Bank";      //  created AP name
char pass[] = "besl";         // (not supported yet)

float volts = 0;
float amps = 0;
float bhp = 0;
int voltsint = 0;
int ampsint = 0;
int bhpint = 0;

int status = WL_IDLE_STATUS;
//Adafruit_WINC1500Server server(80);
WiFiServer server(80);
IPAddress ip;

// *****  Sub Routines  *****

void printWifiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address:
  //IPAddress ip = WiFi.localIP();
  ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
  // print where to go in a browser:
  Serial.print("To see this page, open a browser to http://");
  Serial.println(ip);
}

// *****  Setup  *****

void setup() {

#ifdef WINC_EN
  pinMode(WINC_EN, OUTPUT);
  digitalWrite(WINC_EN, HIGH);
#endif

WiFi.setPins(WINC_CS, WINC_IRQ, WINC_RST);

  while (!Serial);
  Serial.begin(115200);      // initialize serial communication

  // change the ADC resolution to 12 bit
  analogReadResolution(12);

  Serial.println("Access Point Web Server");

  pinMode(LED_PIN, OUTPUT);             // set the LED pin mode
  pinMode(a_button, INPUT_PULLUP);      // set buttons a,b & c as inputs with pullups
  pinMode(b_button, INPUT_PULLUP);
  pinMode(c_button, INPUT_PULLUP);

  // check for the presence of the shield:
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi module not present");

    // don't continue
    while (true);
  }

  // print the network name (SSID);
  Serial.print("Creating access point named: ");
  Serial.println(ssid);

  // Create open network. Change this line if you want to create an WEP network:
  if (WiFi.beginAP(ssid) != WL_CONNECTED) {
    Serial.println("Creating access point failed");
    // don't continue
//    while (true);
  }

  // Wait 10 seconds for connection:
  delay(10000);

  // Start the web server on port 80
  server.begin();

  // You're connected now, so print out the status
  printWifiStatus();
}

// *****  Main Program  *****

void loop() {

  // Setup and read the analog inputs
  int sensorReading0 = analogRead(0);
  int sensorReading1 = analogRead(1);

  // Calculate Volts
  volts = sensorReading0  * (2000 / 1023); // 10 bit
  //volts = sensorReading0  * (2000 / 4095); // 12 bit
  Serial.println(volts);
  // Drop the decimal of the V result
  voltsint = (int)volts;

  // Calculate Amps
  amps = sensorReading1  * (2000 / 1023); // 10 bit
  //amps = sensorReading1  * (2000 / 4095); // 12 bit
  Serial.println(amps);
  // Drop the decimal of the A result
  ampsint = (int)amps;

  // If either the Volts or Amps are zero BHP must be zero
  if ((ampsint == 0) || (voltsint == 0))
  {
    bhpint = 0;
  }

  // Otherwise use the results to calculate BHP
  else
  {
    bhp = ((((volts * amps) * 1.098) / 746) + 225);
    // Drop the decimal of the BHP result
    bhpint = (int)bhp;
  }

//  Adafruit_WINC1500Client client = server.available();   // listen for incoming clients
  WiFiClient client = server.available();   // listen for incoming clients

  if (client) {                             // if you get a client,
    Serial.println("new client");           // print a message out the serial port
    //String currentLine = "";                // make a String to hold incoming data from the client

    // an http request ends with a blank line
    boolean currentLineIsBlank = true;
    while (client.connected()) {            // loop while the client's connected
      if (client.available()) {             // if there's bytes to read from the client,
        char c = client.read();             // read a byte, then
        Serial.write(c);                    // print it out the serial monitor
        //        if (c == '\n') {                    // if the byte is a newline character

        if (c == '\n' && currentLineIsBlank) {
          // send a standard http response header
          client.println("HTTP/1.1 200 OK");
          client.println("Content-Type: text/html");
          client.println("Connection: close");  // the connection will be closed after completion of the response
          client.println("Refresh: 1");  // refresh the page automatically every second
          client.println();
          client.println("<!DOCTYPE HTML>");
          client.println("<html>");

          client.print("<b>Neville Hill HST Load Bank</b>");
          client.println("<br />");
          client.println("<br />");

          client.println("<font size = +1>");

          client.print(voltsint);
          client.print("<b> Volts</b>");
          client.println("<br />");

          client.print(ampsint);
          client.print("<b> Amps</b>");
          client.println("<br />");

          client.print(bhpint);
          client.print("<b> BHP</b>");
          client.println("<br />");
          client.println("<br />");

          // read the status of the buttons a, b & c and display on the web page high or low
          if (!digitalRead(a_button)) {
            client.print("<div style='width:200px;height:26px;padding:10px;background-color: green;border:2px solid black;text-align:center;color:white;'><b>Hatches OPEN</b></div>");
          }
          else {
            client.print("<div style='width:200px;height:26px;padding:10px;background-color: red;border:2px solid black;text-align:center;color:white;'><b>Hatches CLOSED</b></div>");
          }

          if (!digitalRead(b_button)) {
            client.print("<div style='width:200px;height:26px;padding:10px;background-color: green;border:2px solid black;text-align:center;color:white;'><b>Air Press OK</b></div>");
          }
          else {
            client.print("<div style='width:200px;height:26px;padding:10px;background-color: red;border:2px solid black;text-align:center;color:white;'><b>Air Press LOW</b></div>");
          }

          if (!digitalRead(c_button)) {
            client.print("<div style='width:200px;height:26px;padding:10px;background-color: green;border:2px solid black;text-align:center;color:white;'><b>Notch On OK</b></div>");
          }
          else {
            client.print("<div style='width:200px;height:26px;padding:10px;background-color: red;border:2px solid black;text-align:center;color:white;'><b>Notch On READY</b></div>");
          }

          client.print("<div style='width:200px;height:26px;padding:10px;background-color: green;border:2px solid black;text-align:center;color:white;'><b>Cage Door CLOSED</b></div>");

          client.print("<div style='width:200px;height:26px;padding:10px;background-color: green;border:2px solid black;text-align:center;color:white;'><b>Power Status OK</b></div>");

          client.print("<div style='width:200px;height:26px;padding:10px;background-color: green;border:2px solid black;text-align:center;color:white;'><b>E-Stop OK</b></div>");

          client.println("</html>");

          break;
        }
        if (c == '\n') {
          // you're starting a new line
          currentLineIsBlank = true;

        }
        else if (c != '\r') {    // if you got anything else but a carriage return character,
          //currentLine += c;      // add it to the end of the currentLine

          // you've gotten a character on the current line
          currentLineIsBlank = false;
        }
      }
    }
    // give the web browser time to receive the data
    delay(1);

    // close the connection:
    client.stop();
    Serial.println("client disconnected");
  }
}
`

**Comment by sandeepmistry** [comment] 2016-10-27 14:45
Hi @driverblock,

Thanks for reporting this, I'm closing it as a duplicate of https://github.com/arduino-libraries/WiFi101/issues/46.

Right now `server.begin()` needs to be called again everytime a device disconnects from the AP. The changes proposed in #77 might fix this, but they need more testing.

**Closed by sandeepmistry** 2016-10-27 14:45 UTC

**Comment by driverblock** [comment] 2016-11-01 19:14
Thanks for looking into it!  I've passed the status along to the adafruit forum user.
