### ISSUE TITLE
Firmware Updater Bricked Wifi 101?

### ISSUE THREAD

**Issue by wrongtarget** [arduino-libraries/WiFi101#41] opened 2016-03-02 23:01 UTC
This is all I get when attempting to upgrade the firmware of the Wifi 101 on my official Arduino Uno:

2016/03/02 14:56:10 Connecting to programmer
2016/03/02 14:56:12 Synch with programmer
2016/03/02 14:56:12 Reading max payload size
2016/03/02 14:56:12 Flashing firmware from '/Wifi101_FirmwareUpdater/firmware/19.4.4/m2m_aio_2b0.bin'
2016/03/02 14:56:12 Error during FlashErase()

Now none of the Wifi101 examples, including Check101FirmwareVersion work.  Could had something gone wrong during the upgrading process? Anything I can do to start anew?

**Comment by sandeepmistry** [comment] 2016-03-03 14:22
Closing duplicate of https://github.com/arduino-libraries/WiFi101-FirmwareUpdater/issues/4.

**Closed by sandeepmistry** 2016-03-03 14:22 UTC
Labels: duplicate
